#!/bin/bash

set -ex

gcloud container clusters create $1 \
  --cluster-version latest \
  --num-nodes 4 \
  --machine-type=n1-standard-4 \
  --zone us-central1-f \
  --project cf-routing-desserts

gcloud container clusters get-credentials $1 \
    --zone us-central1-f \
    --project cf-routing-desserts

kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)

kubectl create namespace istio-system
